# Generated by Django 2.2.1 on 2019-06-02 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='date_time',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='date_time',
            new_name='date_added',
        ),
    ]
